export interface CountryInfo {
  code: string;
  nameZh: string;
  nameEn: string;
  flag: string;
}

export const COUNTRIES_META: Record<string, { nameZh: string; nameEn: string; flag: string }> = {
  CN: { nameZh: '中国', nameEn: 'China', flag: '🇨🇳' },
  US: { nameZh: '美国', nameEn: 'United States', flag: '🇺🇸' },
  JP: { nameZh: '日本', nameEn: 'Japan', flag: '🇯🇵' },
  FR: { nameZh: '法国', nameEn: 'France', flag: '🇫🇷' },
  ES: { nameZh: '西班牙', nameEn: 'Spain', flag: '🇪🇸' },
  IN: { nameZh: '印度', nameEn: 'India', flag: '🇮🇳' },
  KR: { nameZh: '韩国', nameEn: 'South Korea', flag: '🇰🇷' },
  GB: { nameZh: '英国', nameEn: 'United Kingdom', flag: '🇬🇧' },
  TR: { nameZh: '土耳其', nameEn: 'Turkey', flag: '🇹🇷' },
  DE: { nameZh: '德国', nameEn: 'Germany', flag: '🇩🇪' },
  IR: { nameZh: '伊朗', nameEn: 'Iran', flag: '🇮🇷' },
  RO: { nameZh: '罗马尼亚', nameEn: 'Romania', flag: '🇷🇴' },
  MX: { nameZh: '墨西哥', nameEn: 'Mexico', flag: '🇲🇽' },
  PL: { nameZh: '波兰', nameEn: 'Poland', flag: '🇵🇱' },
  CA: { nameZh: '加拿大', nameEn: 'Canada', flag: '🇨🇦' },
  MY: { nameZh: '马来西亚', nameEn: 'Malaysia', flag: '🇲🇾' },
  IT: { nameZh: '意大利', nameEn: 'Italy', flag: '🇮🇹' },
  CL: { nameZh: '智利', nameEn: 'Chile', flag: '🇨🇱' },
  ZA: { nameZh: '南非', nameEn: 'South Africa', flag: '🇿🇦' },
  NL: { nameZh: '荷兰', nameEn: 'Netherlands', flag: '🇳🇱' },
  AU: { nameZh: '澳大利亚', nameEn: 'Australia', flag: '🇦🇺' },
  UA: { nameZh: '乌克兰', nameEn: 'Ukraine', flag: '🇺🇦' },
  TW: { nameZh: '中国台湾', nameEn: 'Taiwan', flag: '🇹🇼' },
  TH: { nameZh: '泰国', nameEn: 'Thailand', flag: '🇹🇭' },
  SA: { nameZh: '沙特阿拉伯', nameEn: 'Saudi Arabia', flag: '🇸🇦' },
  IL: { nameZh: '以色列', nameEn: 'Israel', flag: '🇮🇱' },
  HU: { nameZh: '匈牙利', nameEn: 'Hungary', flag: '🇭🇺' },
  RU: { nameZh: '俄罗斯', nameEn: 'Russia', flag: '🇷🇺' },
  BE: { nameZh: '比利时', nameEn: 'Belgium', flag: '🇧🇪' },
  VN: { nameZh: '越南', nameEn: 'Vietnam', flag: '🇻🇳' },
  AT: { nameZh: '奥地利', nameEn: 'Austria', flag: '🇦🇹' },
  FI: { nameZh: '芬兰', nameEn: 'Finland', flag: '🇫🇮' },
  CZ: { nameZh: '捷克', nameEn: 'Czech Republic', flag: '🇨🇿' },
  PH: { nameZh: '菲律宾', nameEn: 'Philippines', flag: '🇵🇭' },
  SE: { nameZh: '瑞典', nameEn: 'Sweden', flag: '🇸🇪' },
  NO: { nameZh: '挪威', nameEn: 'Norway', flag: '🇳🇴' },
  BR: { nameZh: '巴西', nameEn: 'Brazil', flag: '🇧🇷' },
  NZ: { nameZh: '新西兰', nameEn: 'New Zealand', flag: '🇳🇿' },
  PK: { nameZh: '巴基斯坦', nameEn: 'Pakistan', flag: '🇵🇰' },
  NP: { nameZh: '尼泊尔', nameEn: 'Nepal', flag: '🇳🇵' },
  BA: { nameZh: '波黑', nameEn: 'Bosnia and Herzegovina', flag: '🇧🇦' },
  HR: { nameZh: '克罗地亚', nameEn: 'Croatia', flag: '🇭🇷' },
  BG: { nameZh: '保加利亚', nameEn: 'Bulgaria', flag: '🇧🇬' },
  JO: { nameZh: '约旦', nameEn: 'Jordan', flag: '🇯🇴' },
  RS: { nameZh: '塞尔维亚', nameEn: 'Serbia', flag: '🇷🇸' },
  AE: { nameZh: '阿联酋', nameEn: 'United Arab Emirates', flag: '🇦🇪' },
  CH: { nameZh: '瑞士', nameEn: 'Switzerland', flag: '🇨🇭' },
  GR: { nameZh: '希腊', nameEn: 'Greece', flag: '🇬🇷' },
  PT: { nameZh: '葡萄牙', nameEn: 'Portugal', flag: '🇵🇹' },
  CO: { nameZh: '哥伦比亚', nameEn: 'Colombia', flag: '🇨🇴' },
  KZ: { nameZh: '哈萨克斯坦', nameEn: 'Kazakhstan', flag: '🇰🇿' },
  SK: { nameZh: '斯洛伐克', nameEn: 'Slovakia', flag: '🇸🇰' },
  CY: { nameZh: '塞浦路斯', nameEn: 'Cyprus', flag: '🇨🇾' },
  SG: { nameZh: '新加坡', nameEn: 'Singapore', flag: '🇸🇬' },
  ID: { nameZh: '印度尼西亚', nameEn: 'Indonesia', flag: '🇮🇩' },
  QA: { nameZh: '卡塔尔', nameEn: 'Qatar', flag: '🇶🇦' },
  DK: { nameZh: '丹麦', nameEn: 'Denmark', flag: '🇩🇰' },
  IE: { nameZh: '爱尔兰', nameEn: 'Ireland', flag: '🇮🇪' },
  AR: { nameZh: '阿根廷', nameEn: 'Argentina', flag: '🇦🇷' },
  PE: { nameZh: '秘鲁', nameEn: 'Peru', flag: '🇵🇪' },
  EG: { nameZh: '埃及', nameEn: 'Egypt', flag: '🇪🇬' },
  KE: { nameZh: '肯尼亚', nameEn: 'Kenya', flag: '🇰🇪' },
  NG: { nameZh: '尼日利亚', nameEn: 'Nigeria', flag: '🇳🇬' },
  MN: { nameZh: '蒙古', nameEn: 'Mongolia', flag: '🇲🇳' },
  KW: { nameZh: '科威特', nameEn: 'Kuwait', flag: '🇰🇼' },
  RE: { nameZh: '留尼汪', nameEn: 'Reunion', flag: '🇷🇪' },
  XK: { nameZh: '科索沃', nameEn: 'Kosovo', flag: '🇽🇰' },
  UZ: { nameZh: '乌兹别克斯坦', nameEn: 'Uzbekistan', flag: '🇺🇿' },
  HK: { nameZh: '中国香港', nameEn: 'Hong Kong', flag: '🇭🇰' },
  LK: { nameZh: '斯里兰卡', nameEn: 'Sri Lanka', flag: '🇱🇰' },
  ET: { nameZh: '埃塞俄比亚', nameEn: 'Ethiopia', flag: '🇪🇹' },
  KG: { nameZh: '吉尔吉斯斯坦', nameEn: 'Kyrgyzstan', flag: '🇰🇬' },
  CW: { nameZh: '库拉索', nameEn: 'Curacao', flag: '🇨🇼' },
  UG: { nameZh: '乌干达', nameEn: 'Uganda', flag: '🇺🇬' },
  BD: { nameZh: '孟加拉国', nameEn: 'Bangladesh', flag: '🇧🇩' },
  IS: { nameZh: '冰岛', nameEn: 'Iceland', flag: '🇮🇸' },
  MO: { nameZh: '中国澳门', nameEn: 'Macau', flag: '🇲🇴' },
  SV: { nameZh: '萨尔瓦多', nameEn: 'El Salvador', flag: '🇸🇻' },
  BH: { nameZh: '巴林', nameEn: 'Bahrain', flag: '🇧🇭' },
  LA: { nameZh: '老挝', nameEn: 'Laos', flag: '🇱🇦' },
  LT: { nameZh: '立陶宛', nameEn: 'Lithuania', flag: '🇱🇹' },
  PR: { nameZh: '波多黎各', nameEn: 'Puerto Rico', flag: '🇵🇷' },
  IQ: { nameZh: '伊拉克', nameEn: 'Iraq', flag: '🇮🇶' },
  MK: { nameZh: '北马其顿', nameEn: 'North Macedonia', flag: '🇲🇰' },
  BO: { nameZh: '玻利维亚', nameEn: 'Bolivia', flag: '🇧🇴' },
  EC: { nameZh: '厄瓜多尔', nameEn: 'Ecuador', flag: '🇪🇨' },
  EE: { nameZh: '爱沙尼亚', nameEn: 'Estonia', flag: '🇪🇪' },
  TJ: { nameZh: '塔吉克斯坦', nameEn: 'Tajikistan', flag: '🇹🇯' },
  MM: { nameZh: '缅甸', nameEn: 'Myanmar', flag: '🇲🇲' },
  DZ: { nameZh: '阿尔及利亚', nameEn: 'Algeria', flag: '🇩🇿' },
  TM: { nameZh: '土库曼斯坦', nameEn: 'Turkmenistan', flag: '🇹🇲' },
  AF: { nameZh: '阿富汗', nameEn: 'Afghanistan', flag: '🇦🇫' },
  ML: { nameZh: '马里', nameEn: 'Mali', flag: '🇲🇱' },
  GE: { nameZh: '格鲁吉亚', nameEn: 'Georgia', flag: '🇬🇪' },
  GT: { nameZh: '危地马拉', nameEn: 'Guatemala', flag: '🇬🇹' },
  GN: { nameZh: '几内亚', nameEn: 'Guinea', flag: '🇬🇳' },
  CI: { nameZh: '科特迪瓦', nameEn: 'Ivory Coast', flag: '🇨🇮' },
  GH: { nameZh: '加纳', nameEn: 'Ghana', flag: '🇬🇭' },
};

export function getCountryInfo(code: string): CountryInfo {
  const c = COUNTRIES_META[code.toUpperCase()];
  if (c) {
    return {
      code: code.toUpperCase(),
      nameZh: c.nameZh,
      nameEn: c.nameEn,
      flag: c.flag,
    };
  }
  return {
    code: code.toUpperCase(),
    nameZh: code,
    nameEn: code,
    flag: '🌐',
  };
}
